name: tese-env
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _py-xgboost-mutex=2.0
  - _r-mutex=1.0.1
  - absl-py=2.2.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.11.14
  - aiosignal=1.3.2
  - alsa-lib=1.2.13
  - anyio=4.9.0
  - aom=3.9.1
  - argcomplete=3.6.2
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arpack=3.9.1
  - array-api-compat=1.11.2
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - async-timeout=5.0.1
  - attr=2.5.1
  - attrs=25.3.0
  - aws-c-auth=0.8.6
  - aws-c-cal=0.8.7
  - aws-c-common=0.12.0
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.4
  - aws-c-http=0.9.4
  - aws-c-io=0.17.0
  - aws-c-mqtt=0.12.2
  - aws-c-s3=0.7.13
  - aws-c-sdkutils=0.2.3
  - aws-checksums=0.2.3
  - aws-crt-cpp=0.31.0
  - aws-sdk-cpp=1.11.510
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - babel=2.17.0
  - beautifulsoup4=4.13.4
  - binutils_impl_linux-64=2.43
  - bioconductor-beachmat=2.18.0
  - bioconductor-biobase=2.62.0
  - bioconductor-biocgenerics=0.48.1
  - bioconductor-biocneighbors=1.20.0
  - bioconductor-biocparallel=1.36.0
  - bioconductor-biocsingular=1.18.0
  - bioconductor-bluster=1.12.0
  - bioconductor-data-packages=20250401
  - bioconductor-delayedarray=0.28.0
  - bioconductor-delayedmatrixstats=1.24.0
  - bioconductor-edger=4.0.16
  - bioconductor-genomeinfodb=1.38.1
  - bioconductor-genomeinfodbdata=1.2.11
  - bioconductor-genomicranges=1.54.1
  - bioconductor-iranges=2.36.0
  - bioconductor-limma=3.58.1
  - bioconductor-matrixgenerics=1.14.0
  - bioconductor-metapod=1.10.0
  - bioconductor-s4arrays=1.2.0
  - bioconductor-s4vectors=0.40.2
  - bioconductor-scaledmatrix=1.10.0
  - bioconductor-scran=1.30.0
  - bioconductor-scuttle=1.12.0
  - bioconductor-singlecellexperiment=1.24.0
  - bioconductor-sparsearray=1.2.2
  - bioconductor-sparsematrixstats=1.14.0
  - bioconductor-summarizedexperiment=1.32.0
  - bioconductor-xvector=0.42.0
  - bioconductor-zlibbioc=1.48.0
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - blinker=1.9.0
  - blosc=1.21.6
  - bottleneck=1.4.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bwidget=1.10.1
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.8.3
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.5.2
  - cairo=1.18.4
  - certifi=2025.8.3
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - chex=0.1.88
  - click=8.1.8
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.1
  - cryptography=44.0.2
  - cuda-cccl_linux-64=12.8.90
  - cuda-crt-dev_linux-64=12.8.93
  - cuda-crt-tools=12.8.93
  - cuda-cudart=12.8.90
  - cuda-cudart-dev_linux-64=12.8.90
  - cuda-cudart-static_linux-64=12.8.90
  - cuda-cudart_linux-64=12.8.90
  - cuda-cuobjdump=12.8.90
  - cuda-cupti=12.8.90
  - cuda-cupti-dev=12.8.90
  - cuda-nvcc-tools=12.8.93
  - cuda-nvdisasm=12.8.90
  - cuda-nvrtc=12.8.93
  - cuda-nvtx=12.8.90
  - cuda-nvvm-tools=12.8.93
  - cuda-version=12.8
  - cudnn=9.8.0.87
  - curl=8.13.0
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - dav1d=1.2.1
  - dbus=1.13.6
  - debugpy=1.8.13
  - decorator=5.2.1
  - defusedxml=0.7.1
  - docrep=0.3.2
  - double-conversion=3.3.1
  - et_xmlfile=2.0.0
  - etils=1.12.2
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.4
  - filelock=3.18.0
  - flax=0.10.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.56.0
  - fqdn=1.5.1
  - freetype=2.13.3
  - fribidi=1.0.10
  - frozenlist=1.5.0
  - fsspec=2025.3.0
  - gcc_impl_linux-64=14.2.0
  - gcsfs=2025.3.0
  - gflags=2.2.2
  - gfortran_impl_linux-64=14.2.0
  - git-lfs=3.6.1
  - glog=0.7.1
  - glpk=5.0
  - gmp=6.3.0
  - gmpy2=2.1.5
  - google-api-core=2.24.2
  - google-auth=2.38.0
  - google-auth-oauthlib=1.2.1
  - google-cloud-core=2.4.3
  - google-cloud-storage=3.1.0
  - google-crc32c=1.7.1
  - google-resumable-media=2.7.2
  - googleapis-common-protos=1.69.2
  - graphite2=1.3.13
  - grpcio=1.71.0
  - gsl=2.7
  - gxx_impl_linux-64=14.2.0
  - h11=0.14.0
  - h2=4.2.0
  - h5py=3.13.0
  - harfbuzz=10.4.0
  - hdf5=1.14.3
  - hpack=4.1.0
  - httpcore=1.0.7
  - httpx=0.28.1
  - humanize=4.12.2
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - igraph=0.10.15
  - importlib-metadata=8.6.1
  - importlib_resources=6.5.2
  - ipykernel=6.29.5
  - ipython=8.34.0
  - ipywidgets=8.1.5
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.4.2
  - jq=1.5
  - json5=0.12.0
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.12.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.0
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.13
  - kernel-headers_linux-64=2.6.32
  - keyutils=1.6.1
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.43
  - legacy-api-wrap=1.4.1
  - leidenalg=0.10.2
  - lerc=4.0.0
  - libabseil=20250127.1
  - libaec=1.1.3
  - libarrow=19.0.1
  - libarrow-acero=19.0.1
  - libarrow-dataset=19.0.1
  - libarrow-substrait=19.0.1
  - libavif16=1.2.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.75
  - libcblas=3.9.0
  - libclang-cpp19.1=19.1.7
  - libclang13=20.1.1
  - libcrc32c=1.1.2
  - libcublas=12.8.4.1
  - libcublas-dev=12.8.4.1
  - libcudss=0.5.0.16
  - libcufft=11.3.3.83
  - libcufft-dev=11.3.3.83
  - libcufile=1.13.1.3
  - libcups=2.3.3
  - libcurand=10.3.9.90
  - libcurand-dev=10.3.9.90
  - libcurl=8.13.0
  - libcusolver=11.7.3.90
  - libcusolver-dev=11.7.3.90
  - libcusparse=12.5.8.93
  - libcusparse-dev=12.5.8.93
  - libdeflate=1.23
  - libdrm=2.4.124
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.4
  - libffi=3.4.6
  - libgcc=15.1.0
  - libgcc-devel_linux-64=14.2.0
  - libgcc-ng=15.1.0
  - libgcrypt-lib=1.11.0
  - libgfortran=15.1.0
  - libgfortran-ng=15.1.0
  - libgfortran5=15.1.0
  - libgit2=1.8.4
  - libgl=1.7.0
  - libglib=2.82.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.1.0
  - libgoogle-cloud=2.36.0
  - libgoogle-cloud-storage=2.36.0
  - libgpg-error=1.51
  - libgrpc=1.71.0
  - libhwloc=2.11.2
  - libiconv=1.18
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libleidenalg=0.11.1
  - libllvm19=19.1.7
  - libllvm20=20.1.1
  - liblzma=5.6.4
  - libmagma=2.9.0
  - libnghttp2=1.64.0
  - libnl=3.11.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libnvjitlink=12.8.93
  - libopenblas=0.3.29
  - libopengl=1.7.0
  - libopentelemetry-cpp=1.19.0
  - libopentelemetry-cpp-headers=1.19.0
  - libparquet=19.0.1
  - libpciaccess=0.18
  - libpng=1.6.47
  - libpq=17.4
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libsanitizer=14.2.0
  - libsodium=1.0.20
  - libsqlite=3.49.1
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-devel_linux-64=14.2.0
  - libstdcxx-ng=15.1.0
  - libsystemd0=257.4
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libtorch=2.6.0
  - libudev1=257.4
  - libutf8proc=2.10.0
  - libuuid=2.38.1
  - libuv=1.50.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxgboost=2.1.4
  - libxkbcommon=1.8.1
  - libxml2=2.13.6
  - libxslt=1.1.39
  - libzlib=1.3.1
  - lightning=2.5.1
  - lightning-utilities=0.14.2
  - llvm-openmp=20.1.1
  - llvmlite=0.44.0
  - lz4-c=1.10.0
  - make=4.4.1
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib=3.10.1
  - matplotlib-base=3.10.1
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - mistune=3.1.3
  - ml-collections=1.0.0
  - ml_dtypes=0.5.1
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - msgpack-python=1.1.0
  - mudata=0.3.1
  - multidict=6.2.0
  - multipledispatch=0.6.0
  - munkres=1.1.4
  - mysql-common=9.0.1
  - mysql-libs=9.0.1
  - natsort=8.4.0
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - nccl=2.26.2.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - nlohmann_json=3.11.3
  - nomkl=1.0
  - notebook=7.4.0
  - notebook-shim=0.2.4
  - numba=0.61.0
  - numexpr=2.10.2
  - numpyro=0.18.0
  - oauthlib=3.2.2
  - openjpeg=2.5.3
  - openldap=2.6.9
  - openpyxl=3.1.5
  - openssl=3.5.2
  - opt_einsum=3.4.0
  - optax=0.2.4
  - optree=0.14.1
  - orbax-checkpoint=0.6.4
  - orc=2.1.1
  - overrides=7.7.0
  - packaging=24.2
  - pandas=2.2.3
  - pandoc=3.6.4
  - pandocfilters=1.5.0
  - pango=1.56.3
  - parso=0.8.4
  - patsy=1.0.1
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.0
  - pixman=0.44.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.7
  - polars=1.26.0
  - prometheus-cpp=1.3.0
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.50
  - propcache=0.2.1
  - proto-plus=1.26.1
  - protobuf=5.29.3
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - py-xgboost=2.1.4
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.1
  - pybind11=2.13.6
  - pybind11-abi=4
  - pybind11-global=2.13.6
  - pycparser=2.22
  - pygments=2.19.1
  - pyjwt=2.10.1
  - pynndescent=0.5.13
  - pyopenssl=25.0.0
  - pyparsing=3.2.2
  - pyro-api=0.1.2
  - pyro-ppl=1.9.1
  - pyside6=6.8.2
  - pysocks=1.7.1
  - python=3.10.16
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.1
  - python-igraph=0.11.8
  - python-json-logger=2.0.7
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytorch-lightning=2.5.1
  - pytz=2025.2
  - pyu2f=0.1.5
  - pyyaml=6.0.2
  - pyzmq=26.3.0
  - qhull=2020.2
  - qt6-main=6.8.2
  - r-abind=1.4_5
  - r-askpass=1.2.1
  - r-assertthat=0.2.1
  - r-backports=1.5.0
  - r-base=4.3.3
  - r-base64enc=0.1_3
  - r-bh=1.87.0_1
  - r-bit=4.6.0
  - r-bit64=4.6.0_1
  - r-bitops=1.0_9
  - r-blob=1.2.4
  - r-boot=1.3_31
  - r-brew=1.0_10
  - r-brio=1.1.5
  - r-broom=1.0.8
  - r-bslib=0.9.0
  - r-cachem=1.1.0
  - r-callr=3.7.6
  - r-caret=6.0_94
  - r-cellranger=1.1.0
  - r-class=7.3_23
  - r-cli=3.6.4
  - r-clipr=0.8.0
  - r-clock=0.7.3
  - r-cluster=2.1.8.1
  - r-codetools=0.2_20
  - r-colorspace=2.1_1
  - r-commonmark=1.9.5
  - r-conflicted=1.2.0
  - r-cpp11=0.5.2
  - r-crayon=1.5.3
  - r-credentials=2.0.2
  - r-curl=6.2.2
  - r-data.table=1.17.0
  - r-dbi=1.2.3
  - r-dbplyr=2.5.0
  - r-desc=1.4.3
  - r-devtools=2.4.5
  - r-diagram=1.6.5
  - r-diffobj=0.3.6
  - r-digest=0.6.37
  - r-downlit=0.4.4
  - r-dplyr=1.1.4
  - r-dqrng=0.3.2
  - r-dtplyr=1.3.1
  - r-e1071=1.7_16
  - r-ellipsis=0.3.2
  - r-essentials=4.3.1
  - r-evaluate=1.0.3
  - r-fansi=1.0.6
  - r-farver=2.1.2
  - r-fastmap=1.2.0
  - r-fontawesome=0.5.3
  - r-forcats=1.0.0
  - r-foreach=1.5.2
  - r-foreign=0.8_90
  - r-formatr=1.14
  - r-fs=1.6.6
  - r-futile.logger=1.4.3
  - r-futile.options=1.0.1
  - r-future=1.40.0
  - r-future.apply=1.11.3
  - r-gargle=1.5.2
  - r-generics=0.1.3
  - r-gert=2.1.4
  - r-ggplot2=3.5.2
  - r-gh=1.4.1
  - r-gitcreds=0.1.2
  - r-glmnet=4.1_8
  - r-globals=0.17.0
  - r-glue=1.8.0
  - r-googledrive=2.1.1
  - r-googlesheets4=1.1.1
  - r-gower=1.0.1
  - r-gsl=2.1_8
  - r-gtable=0.3.6
  - r-hardhat=1.4.1
  - r-haven=2.5.4
  - r-highr=0.11
  - r-hms=1.1.3
  - r-htmltools=0.5.8.1
  - r-htmlwidgets=1.6.4
  - r-httpuv=1.6.15
  - r-httr=1.4.7
  - r-httr2=1.1.2
  - r-ids=1.0.1
  - r-igraph=2.0.3
  - r-ini=0.3.1
  - r-ipred=0.9_15
  - r-irdisplay=1.1
  - r-irkernel=1.3.2
  - r-irlba=2.3.5.1
  - r-isoband=0.2.7
  - r-iterators=1.0.14
  - r-jquerylib=0.1.4
  - r-jsonlite=2.0.0
  - r-kernsmooth=2.23_26
  - r-knitr=1.50
  - r-labeling=0.4.3
  - r-lambda.r=1.2.4
  - r-later=1.4.2
  - r-lattice=0.22_7
  - r-lava=1.8.1
  - r-lifecycle=1.0.4
  - r-listenv=0.9.1
  - r-locfit=1.5_9.12
  - r-lubridate=1.9.4
  - r-magrittr=2.0.3
  - r-mass=7.3_60
  - r-matrix=1.6_5
  - r-matrixstats=1.5.0
  - r-memoise=2.0.1
  - r-mgcv=1.9_3
  - r-mime=0.13
  - r-miniui=0.1.2
  - r-modelmetrics=1.2.2.2
  - r-modelr=0.1.11
  - r-munsell=0.5.1
  - r-nlme=3.1_168
  - r-nnet=7.3_20
  - r-numderiv=2016.8_1.1
  - r-openssl=2.3.2
  - r-parallelly=1.43.0
  - r-pbdzmq=0.3_14
  - r-pillar=1.10.2
  - r-pkgbuild=1.4.7
  - r-pkgconfig=2.0.3
  - r-pkgdown=2.1.2
  - r-pkgload=1.4.0
  - r-plyr=1.8.9
  - r-praise=1.0.0
  - r-prettyunits=1.2.0
  - r-proc=1.18.5
  - r-processx=3.8.6
  - r-prodlim=2024.06.25
  - r-profvis=0.4.0
  - r-progress=1.2.3
  - r-progressr=0.15.1
  - r-promises=1.3.2
  - r-proxy=0.4_27
  - r-ps=1.9.1
  - r-purrr=1.0.4
  - r-quantmod=0.4.27
  - r-r6=2.6.1
  - r-ragg=1.4.0
  - r-randomforest=4.7_1.2
  - r-rappdirs=0.3.3
  - r-rcmdcheck=1.4.0
  - r-rcolorbrewer=1.1_3
  - r-rcpp=1.0.14
  - r-rcppeigen=0.3.4.0.2
  - r-rcpphnsw=0.6.0
  - r-rcurl=1.98_1.16
  - r-readr=2.1.5
  - r-readxl=1.4.5
  - r-recipes=1.3.0
  - r-recommended=4.3.1
  - r-rematch=2.0.0
  - r-rematch2=2.1.2
  - r-remotes=2.5.0
  - r-repr=1.1.7
  - r-reprex=2.1.1
  - r-reshape2=1.4.4
  - r-rlang=1.1.6
  - r-rmarkdown=2.29
  - r-roxygen2=7.3.2
  - r-rpart=4.1.24
  - r-rprojroot=2.0.4
  - r-rstudioapi=0.17.1
  - r-rsvd=1.0.5
  - r-rversions=2.1.2
  - r-rvest=1.0.4
  - r-sass=0.4.10
  - r-scales=1.3.0
  - r-selectr=0.4_2
  - r-sessioninfo=1.2.3
  - r-shape=1.4.6.1
  - r-shiny=1.10.0
  - r-sitmo=2.0.2
  - r-snow=0.4_4
  - r-sourcetools=0.1.7_1
  - r-sparsevctrs=0.3.3
  - r-spatial=7.3_18
  - r-squarem=2021.1
  - r-statmod=1.5.0
  - r-stringi=1.8.7
  - r-stringr=1.5.1
  - r-survival=3.8_3
  - r-sys=3.4.3
  - r-systemfonts=1.2.1
  - r-testthat=3.2.3
  - r-textshaping=0.3.7
  - r-tibble=3.2.1
  - r-tidyr=1.3.1
  - r-tidyselect=1.2.1
  - r-tidyverse=2.0.0
  - r-timechange=0.3.0
  - r-timedate=4041.110
  - r-tinytex=0.57
  - r-ttr=0.24.4
  - r-tzdb=0.5.0
  - r-urlchecker=1.0.1
  - r-usethis=3.1.0
  - r-utf8=1.2.4
  - r-uuid=1.2_1
  - r-vctrs=0.6.5
  - r-viridislite=0.4.2
  - r-vroom=1.6.5
  - r-waldo=0.6.1
  - r-whisker=0.4.1
  - r-withr=3.0.2
  - r-xfun=0.52
  - r-xml=3.99_0.17
  - r-xml2=1.3.8
  - r-xopen=1.0.1
  - r-xtable=1.8_4
  - r-xts=0.14.1
  - r-yaml=2.3.10
  - r-zip=2.3.2
  - r-zoo=1.8_14
  - rav1e=0.6.6
  - rdma-core=56.0
  - re2=2024.07.02
  - readline=8.2
  - referencing=0.36.2
  - requests=2.32.3
  - requests-oauthlib=2.0.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.9.4
  - rpds-py=0.24.0
  - rpy2=3.5.11
  - rsa=4.9
  - s2n=1.5.14
  - scanpy=1.11.0
  - scikit-learn=1.5.2
  - scikit-misc=0.5.1
  - scipy=1.14.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - sed=4.8
  - send2trash=1.8.3
  - session-info2=0.1.2
  - setuptools=75.8.2
  - simplegeneric=0.8.1
  - six=1.17.0
  - sleef=3.8
  - snappy=1.2.1
  - sniffio=1.3.1
  - soupsieve=2.5
  - sparse=0.15.5
  - stack_data=0.6.3
  - statsmodels=0.14.4
  - svt-av1=3.0.1
  - sysroot_linux-64=2.12
  - tapi=1300.6.5
  - tbb=2022.0.0
  - tensorstore=0.1.65
  - terminado=0.18.1
  - texttable=1.7.0
  - threadpoolctl=3.6.0
  - tinycss2=1.4.0
  - tk=8.6.13
  - tktable=2.10
  - toml=0.10.2
  - tomli=2.2.1
  - tomlkit=0.13.2
  - toolz=1.0.0
  - torchmetrics=1.7.0
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20241206
  - typing_utils=0.1.0
  - tzdata=2025b
  - tzlocal=5.3
  - umap-learn=0.5.7
  - unicodedata2=16.0.0
  - uri-template=1.3.0
  - urllib3=2.3.0
  - wayland=1.23.1
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - widgetsnbextension=4.0.13
  - xarray=2025.3.0
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xgboost=2.1.4
  - xkeyboard-config=2.43
  - xmltodict=0.14.2
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxt=1.3.1
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - yaml=0.2.5
  - yarl=1.18.3
  - yq=3.4.3
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
    - anndata==0.11.4
    - datasets==4.1.0
    - dill==0.4.0
    - huggingface-hub==0.29.3
    - jax==0.4.35
    - jax-cuda12-pjrt==0.5.2
    - jax-cuda12-plugin==0.5.2
    - jaxlib==0.4.35
    - markdown==3.7
    - matplotlib-venn==1.1.2
    - multiprocess==0.70.16
    - numpy==1.26.4
    - nvidia-cublas-cu12==12.4.5.8
    - nvidia-cuda-cupti-cu12==12.4.127
    - nvidia-cuda-nvrtc-cu12==12.4.127
    - nvidia-cuda-runtime-cu12==12.4.127
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.2.1.3
    - nvidia-curand-cu12==10.3.5.147
    - nvidia-cusolver-cu12==11.6.1.9
    - nvidia-cusparse-cu12==12.3.1.170
    - nvidia-nccl-cu12==2.21.5
    - nvidia-nvjitlink-cu12==12.4.127
    - nvidia-nvtx-cu12==12.4.127
    - pyarrow==21.0.0
    - scvi-tools==1.3.0
    - sympy==1.13.1
    - tensorboard==2.19.0
    - tensorboard-data-server==0.7.2
    - torch==2.5.1
    - triton==3.1.0
    - typing-extensions==4.13.0
    - werkzeug==3.1.3
    - xxhash==3.5.0
