name: scfoundation_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - arrow-cpp=19.0.0
  - asttokens=3.0.0
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.11.212
  - backcall=0.2.0
  - blas=1.0
  - boost-cpp=1.82.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.2.25
  - comm=0.2.2
  - debugpy=1.8.11
  - decorator=5.2.1
  - entrypoints=0.4
  - executing=2.2.0
  - gflags=2.2.2
  - glog=0.5.0
  - icu=73.1
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.12.0
  - jedi=0.19.2
  - jupyter_client=7.3.4
  - jupyter_core=5.7.2
  - krb5=1.20.1
  - ld_impl_linux-64=2.40
  - libabseil=20250127.0
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.12.1
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libgrpc=1.71.0
  - libnghttp2=1.57.0
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libsodium=1.0.18
  - libssh2=1.11.1
  - libstdcxx-ng=11.2.0
  - libthrift=0.15.0
  - lz4-c=1.9.4
  - matplotlib-inline=0.1.7
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - numpy-base=1.26.4
  - openssl=3.0.16
  - orc=2.1.1
  - packaging=25.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.1
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - prompt_toolkit=3.0.51
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow=19.0.0
  - pygments=2.19.1
  - python=3.9.21
  - python-dateutil=2.9.0.post0
  - python_abi=3.9
  - pyzmq=26.2.0
  - re2=2024.07.02
  - readline=8.2
  - s2n=1.3.27
  - setuptools=78.1.1
  - six=1.17.0
  - snappy=1.2.1
  - sqlite=3.45.3
  - stack_data=0.6.3
  - tbb=2021.8.0
  - tk=8.6.14
  - tornado=6.1
  - traitlets=5.14.3
  - typing_extensions=4.13.2
  - utf8proc=2.6.1
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
    - anndata==0.10.9
    - array-api-compat==1.11.2
    - certifi==2025.4.26
    - charset-normalizer==3.4.2
    - cmake==3.25.0
    - contourpy==1.3.0
    - cycler==0.12.1
    - einops==0.8.1
    - exceptiongroup==1.3.0
    - filelock==3.13.1
    - fonttools==4.58.0
    - fsspec==2025.3.2
    - get-annotations==0.1.2
    - h5py==3.13.0
    - hyper-connections==0.1.15
    - idna==3.10
    - importlib-resources==6.5.2
    - jinja2==3.1.4
    - joblib==1.5.0
    - kiwisolver==1.4.7
    - legacy-api-wrap==1.4.1
    - lit==15.0.7
    - llvmlite==0.43.0
    - local-attention==1.11.1
    - markupsafe==2.1.5
    - matplotlib==3.9.4
    - mpmath==1.3.0
    - natsort==8.4.0
    - networkx==3.2.1
    - numba==0.60.0
    - numpy==1.24.4
    - nvidia-cublas-cu12==12.6.4.1
    - nvidia-cuda-cupti-cu12==12.6.80
    - nvidia-cuda-nvrtc-cu12==12.6.77
    - nvidia-cuda-runtime-cu12==12.6.77
    - nvidia-cudnn-cu12==9.5.1.17
    - nvidia-cufft-cu12==11.3.0.4
    - nvidia-cufile-cu12==1.11.1.6
    - nvidia-curand-cu12==10.3.7.77
    - nvidia-cusolver-cu12==11.7.1.2
    - nvidia-cusparse-cu12==12.5.4.2
    - nvidia-cusparselt-cu12==0.6.3
    - nvidia-nccl-cu12==2.26.2
    - nvidia-nvjitlink-cu12==12.6.85
    - nvidia-nvtx-cu12==12.6.77
    - pandas==2.2.3
    - patsy==1.0.1
    - pillow==11.2.1
    - polars==1.29.0
    - pynndescent==0.5.13
    - pyparsing==3.2.3
    - pytz==2025.2
    - scanpy==1.10.3
    - scikit-learn==1.6.1
    - scipy==1.13.1
    - seaborn==0.13.2
    - session-info==1.0.1
    - statsmodels==0.14.4
    - stdlib-list==0.11.1
    - sympy==1.13.3
    - threadpoolctl==3.6.0
    - torch==2.0.1+cu117
    - torchaudio==2.0.2+cu117
    - torchvision==0.15.2+cu117
    - tqdm==4.67.1
    - triton==2.0.0
    - typing-extensions==4.12.2
    - tzdata==2025.2
    - umap-learn==0.5.7
    - urllib3==2.4.0
    - zipp==3.21.0
