name: scgpt_2
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - binutils_impl_linux-64=2.43
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - cuda-version=11.7
  - cudatoolkit=11.7.1
  - cudatoolkit-dev=11.7.0
  - cudnn=9.10.0.56
  - gcc=11.4.0
  - gcc_impl_linux-64=11.4.0
  - gxx=11.4.0
  - gxx_impl_linux-64=11.4.0
  - kernel-headers_linux-64=3.10.0
  - ld_impl_linux-64=2.43
  - libcudnn=9.10.0.56
  - libcudnn-dev=9.10.0.56
  - libffi=3.4.6
  - libgcc=15.1.0
  - libgcc-devel_linux-64=11.4.0
  - libgcc-ng=15.1.0
  - libgomp=15.1.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnsl=2.0.1
  - libsanitizer=11.4.0
  - libsqlite=3.49.2
  - libstdcxx=15.1.0
  - libstdcxx-devel_linux-64=11.4.0
  - libstdcxx-ng=15.1.0
  - libuuid=2.38.1
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.5.0
  - pip=25.1.1
  - python=3.10.11
  - readline=8.2
  - setuptools=80.1.0
  - sysroot_linux-64=2.17
  - tk=8.6.13
  - wheel=0.45.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - pip:
    - absl-py==2.2.2
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.11.18
    - aiosignal==1.3.2
    - anndata==0.11.4
    - array-api-compat==1.12.0
    - asttokens==3.0.0
    - async-timeout==5.0.1
    - attrs==25.3.0
    - cached-property==2.0.1
    - cell-gears==0.0.2
    - certifi==2025.4.26
    - charset-normalizer==3.4.2
    - chex==0.1.89
    - comm==0.2.2
    - contourpy==1.3.2
    - cycler==0.12.1
    - datasets==2.14.5
    - dcor==0.6
    - debugpy==1.8.14
    - decorator==5.2.1
    - deprecated==1.2.18
    - dill==0.3.7
    - docrep==0.3.2
    - einops==0.8.1
    - et-xmlfile==2.0.0
    - etils==1.12.2
    - exceptiongroup==1.3.0
    - executing==2.2.0
    - filelock==3.18.0
    - flash-attn==1.0.4
    - flax==0.10.6
    - fonttools==4.58.0
    - frozenlist==1.6.0
    - fsspec==2023.6.0
    - grpcio==1.71.0
    - h5py==3.13.0
    - huggingface-hub==0.31.2
    - humanize==4.12.3
    - idna==3.10
    - igraph==0.11.8
    - importlib-resources==6.5.2
    - ipykernel==6.29.5
    - ipython==8.36.0
    - jax==0.6.0
    - jaxlib==0.6.0
    - jedi==0.19.2
    - jinja2==3.1.6
    - joblib==1.5.0
    - jupyter-client==8.6.3
    - jupyter-core==5.7.2
    - kiwisolver==1.4.8
    - legacy-api-wrap==1.4.1
    - leidenalg==0.10.2
    - lightning==2.5.1.post0
    - lightning-utilities==0.14.3
    - llvmlite==0.44.0
    - markdown==3.8
    - markdown-it-py==3.0.0
    - markupsafe==3.0.2
    - matplotlib==3.10.3
    - matplotlib-inline==0.1.7
    - mdurl==0.1.2
    - ml-collections==1.1.0
    - ml-dtypes==0.5.1
    - mpmath==1.3.0
    - msgpack==1.1.0
    - mudata==0.3.1
    - multidict==6.4.3
    - multipledispatch==1.0.0
    - multiprocess==0.70.15
    - natsort==8.4.0
    - nest-asyncio==1.6.0
    - networkx==3.4.2
    - numba==0.61.2
    - numpy==1.24.4
    - numpyro==0.18.0
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cublas-cu12==12.6.4.1
    - nvidia-cuda-cupti-cu12==12.6.80
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-nvrtc-cu12==12.6.77
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cuda-runtime-cu12==12.6.77
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cudnn-cu12==9.5.1.17
    - nvidia-cufft-cu12==11.3.0.4
    - nvidia-cufile-cu12==1.11.1.6
    - nvidia-curand-cu12==10.3.7.77
    - nvidia-cusolver-cu12==11.7.1.2
    - nvidia-cusparse-cu12==12.5.4.2
    - nvidia-cusparselt-cu12==0.6.3
    - nvidia-nccl-cu12==2.26.2
    - nvidia-nvjitlink-cu12==12.6.85
    - nvidia-nvtx-cu12==12.6.77
    - openpyxl==3.1.5
    - opt-einsum==3.4.0
    - optax==0.2.4
    - orbax==0.1.7
    - orbax-checkpoint==0.11.13
    - packaging==24.2
    - pandas==2.2.3
    - parso==0.8.4
    - patsy==1.0.1
    - pexpect==4.9.0
    - pillow==11.2.1
    - platformdirs==4.3.8
    - prompt-toolkit==3.0.51
    - propcache==0.3.1
    - protobuf==6.31.0
    - psutil==7.0.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.3
    - pyarrow==20.0.0
    - pydot==4.0.0
    - pygments==2.19.1
    - pynndescent==0.5.13
    - pyparsing==3.2.3
    - pyro-api==0.1.2
    - pyro-ppl==1.9.1
    - python-dateutil==2.9.0.post0
    - pytorch-lightning==1.9.5
    - pytz==2025.2
    - pyyaml==6.0.2
    - pyzmq==26.4.0
    - requests==2.32.3
    - rich==14.0.0
    - scanpy==1.11.1
    - scgpt==0.2.4
    - scib==1.1.7
    - scikit-learn==1.5.2
    - scikit-misc==0.5.1
    - scipy==1.15.3
    - scvi-tools==0.20.0
    - seaborn==0.13.2
    - session-info2==0.1.2
    - simplejson==3.20.1
    - six==1.17.0
    - sparse==0.16.0
    - stack-data==0.6.3
    - statsmodels==0.14.4
    - sympy==1.14.0
    - tensorboard==2.19.0
    - tensorboard-data-server==0.7.2
    - tensorstore==0.1.75
    - texttable==1.7.0
    - threadpoolctl==3.6.0
    - toolz==1.0.0
    - torch==1.13.0+cu117
    - torchaudio==0.13.0+cu117
    - torchmetrics==1.7.1
    - torchtext==0.14.0
    - torchvision==0.14.0+cu117
    - tornado==6.5
    - tqdm==4.67.1
    - traitlets==5.14.3
    - treescope==0.1.9
    - triton==3.3.0
    - typing-extensions==4.13.2
    - tzdata==2025.2
    - umap-learn==0.5.7
    - urllib3==2.4.0
    - wcwidth==0.2.13
    - werkzeug==3.1.3
    - wrapt==1.17.2
    - xarray==2025.4.0
    - xxhash==3.5.0
    - yarl==1.20.0
    - zipp==3.21.0
